### ISSUE TITLE
cannot compile with mruby 1.2.0

### ISSUE THREAD

**Issue by tsahara** [iij/mruby-iijson#11]
```
CC    ../../../../../../../../home/tsahara/src/mruby/mruby-iijson/src/json.c -> ../../../../../../../../home/tsahara/src/mruby/work/builds/iijson-1.2.0/host/mrbgems/mruby-iijson/src/json.o                                                    
/home/tsahara/src/mruby/mruby-iijson/src/json.c: In function 'json_parse_number2 ':
/home/tsahara/src/mruby/mruby-iijson/src/json.c:324: error: expected ')' before 'MRB_PRId'
/home/tsahara/src/mruby/mruby-iijson/src/json.c:326: warning: too few arguments for format
/home/tsahara/src/mruby/mruby-iijson/src/json.c: In function 'json_parse_number2 ':
/home/tsahara/src/mruby/mruby-iijson/src/json.c:324: error: expected ')' before 'MRB_PRId'
/home/tsahara/src/mruby/mruby-iijson/src/json.c:326: warning: too few arguments for format
rake aborted!
Command failed with status (1): [gcc -g -std=gnu99 -O3 -Wall -Werror-implic...]
```
